Resources:
  itemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.itemTableName}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: "S"
        - AttributeName: SK
          AttributeType: "S"